"""fk de orden de pago

Revision ID: 059e57ad67f6
Revises: e44f04fde9b3
Create Date: 2026-03-12 12:49:31.559469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059e57ad67f6'
down_revision: Union[str, Sequence[str], None] = 'e44f04fde9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrdenPagoDetalle', sa.Column('OrdenPagoId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'OrdenPagoDetalle', 'OrdenDePago', ['OrdenPagoId'], ['OrdenPagoId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'OrdenPagoDetalle', type_='foreignkey')
    op.drop_column('OrdenPagoDetalle', 'OrdenPagoId')
    # ### end Alembic commands ###
