"""documentos-tipo afiliacion

Revision ID: 10cdf88c4a65
Revises: 16a5ec21c90d
Create Date: 2026-03-04 16:00:44.006331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cdf88c4a65'
down_revision: Union[str, Sequence[str], None] = '16a5ec21c90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentoAfiliacion',
    sa.Column('DocumentoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('TipoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('DocumentoId', sa.Integer(), nullable=False),
    sa.Column('RolPersonaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DocumentoId'], ['CatalogoDocumentos.DocumentoId'], ),
    sa.ForeignKeyConstraint(['RolPersonaId'], ['CatalogoRolesPersonas.RolPersonaId'], ),
    sa.ForeignKeyConstraint(['TipoAfiliacionId'], ['CatalogoTiposAfiliacion.TipoAfiliacionId'], ),
    sa.PrimaryKeyConstraint('DocumentoAfiliacionId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentoAfiliacion')
    # ### end Alembic commands ###
