"""catalogo roles de personas

Revision ID: 16a5ec21c90d
Revises: add2602fe93a
Create Date: 2026-03-04 15:48:14.154283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a5ec21c90d'
down_revision: Union[str, Sequence[str], None] = 'add2602fe93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoRolesPersonas',
    sa.Column('RolPersonaId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('RolPersonaId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoRolesPersonas')
    # ### end Alembic commands ###
