"""refactor documento afiliacion6

Revision ID: 2b45b6ee2554
Revises: e534cd6aeba6
Create Date: 2026-03-06 13:34:24.854285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b45b6ee2554'
down_revision: Union[str, Sequence[str], None] = 'e534cd6aeba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentoAfiliacion', sa.Column('DocumentoPersonaId', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('FK__Documento__Docum__14270015'), 'DocumentoAfiliacion', type_='foreignkey')
    op.drop_constraint(op.f('FK__Documento__RolPe__151B244E'), 'DocumentoAfiliacion', type_='foreignkey')
    op.create_foreign_key(None, 'DocumentoAfiliacion', 'CatalogoDocumentosPersonas', ['DocumentoPersonaId'], ['DocumentosPersonasId'])
    op.drop_column('DocumentoAfiliacion', 'DocumentoId')
    op.drop_column('DocumentoAfiliacion', 'RolPersonaId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentoAfiliacion', sa.Column('RolPersonaId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('DocumentoAfiliacion', sa.Column('DocumentoId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'DocumentoAfiliacion', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Documento__RolPe__151B244E'), 'DocumentoAfiliacion', 'CatalogoRolesPersonas', ['RolPersonaId'], ['RolPersonaId'])
    op.create_foreign_key(op.f('FK__Documento__Docum__14270015'), 'DocumentoAfiliacion', 'CatalogoDocumentos', ['DocumentoId'], ['DocumentoId'])
    op.drop_column('DocumentoAfiliacion', 'DocumentoPersonaId')
    # ### end Alembic commands ###
