"""catalogo de documentos

Revision ID: 3275cdb793b5
Revises: d993b2cf9507
Create Date: 2026-03-03 13:41:57.537896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3275cdb793b5'
down_revision: Union[str, Sequence[str], None] = 'd993b2cf9507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoDocumentos',
    sa.Column('DocumentoId', sa.Integer(), nullable=False),
    sa.Column('NombreDocumento', sa.String(length=100), nullable=False),
    sa.Column('Descripcion', sa.String(length=200), nullable=True),
    sa.Column('TipoArchivoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TipoArchivoId'], ['CatalogoTiposArchivo.TipoArchivoId'], ),
    sa.PrimaryKeyConstraint('DocumentoId'),
    sa.UniqueConstraint('NombreDocumento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoDocumentos')
    # ### end Alembic commands ###
