"""equipo temporal jugador tabla

Revision ID: 421ce919ee77
Revises: ad5929969e3a
Create Date: 2026-03-20 15:46:52.501933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421ce919ee77'
down_revision: Union[str, Sequence[str], None] = 'ad5929969e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EquipoTemporalJugador',
    sa.Column('EquipoTemporalJugadorId', sa.Integer(), nullable=False),
    sa.Column('Completo', sa.Boolean(), nullable=False),
    sa.Column('EquipoTemporalId', sa.Integer(), nullable=False),
    sa.Column('PersonaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EquipoTemporalId'], ['EquipoTemporal.EquipoTemporalId'], ),
    sa.ForeignKeyConstraint(['PersonaId'], ['Personas.PersonaId'], ),
    sa.PrimaryKeyConstraint('EquipoTemporalJugadorId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EquipoTemporalJugador')
    # ### end Alembic commands ###
