"""documentos entregados en solicitud

Revision ID: 4b63f11e0289
Revises: 10cdf88c4a65
Create Date: 2026-03-04 16:10:02.734298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b63f11e0289'
down_revision: Union[str, Sequence[str], None] = '10cdf88c4a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentosEntregadosSolicitud',
    sa.Column('DocumentosSolicitudId', sa.Integer(), nullable=False),
    sa.Column('SolicitudId', sa.Integer(), nullable=False),
    sa.Column('DocumentoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('RutaArchivo', sa.String(length=512), nullable=False),
    sa.Column('FechaEntrega', sa.DateTime(), nullable=False),
    sa.Column('FechaValidacion', sa.DateTime(), nullable=True),
    sa.Column('ObservacionesDocumento', sa.String(length=500), nullable=True),
    sa.Column('EstadoValidacionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DocumentoAfiliacionId'], ['DocumentoAfiliacion.DocumentoAfiliacionId'], ),
    sa.ForeignKeyConstraint(['EstadoValidacionId'], ['CatalogoEstadosValidacion.EstadoValidacionId'], ),
    sa.ForeignKeyConstraint(['SolicitudId'], ['Solicitudes.SolicitudId'], ),
    sa.PrimaryKeyConstraint('DocumentosSolicitudId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentosEntregadosSolicitud')
    # ### end Alembic commands ###
