"""agregar tabla roles nueva

Revision ID: 4c3539bb083f
Revises: 0bf03bf9e2d7
Create Date: 2026-03-11 14:32:03.768832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3539bb083f'
down_revision: Union[str, Sequence[str], None] = '0bf03bf9e2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('RolId'),
    sa.UniqueConstraint('Nombre')
    )
    op.add_column('Usuarios', sa.Column('RolId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Usuarios', 'Roles', ['RolId'], ['RolId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Usuarios', type_='foreignkey')
    op.drop_column('Usuarios', 'RolId')
    op.drop_table('Roles')
    # ### end Alembic commands ###
