"""catalogo de proceso de equipo temporal

Revision ID: 4c878bfe0af9
Revises: b154cc696184
Create Date: 2026-03-20 14:06:04.487767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c878bfe0af9'
down_revision: Union[str, Sequence[str], None] = 'b154cc696184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
