"""implement_rbac_models

Revision ID: 590f08aeb259
Revises: 9430dc58adbb
Create Date: 2026-03-24 11:34:15.615509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590f08aeb259'
down_revision: Union[str, Sequence[str], None] = '9430dc58adbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Menus',
    sa.Column('MenuId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Ruta', sa.String(length=255), nullable=True),
    sa.Column('Icono', sa.String(length=100), nullable=True),
    sa.Column('Orden', sa.Integer(), nullable=True),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.Column('MenuPadreId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MenuPadreId'], ['Menus.MenuId'], ),
    sa.PrimaryKeyConstraint('MenuId')
    )
    op.create_table('Permisos',
    sa.Column('PermisoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Slug', sa.String(length=100), nullable=False),
    sa.Column('Descripcion', sa.String(length=255), nullable=True),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('PermisoId'),
    sa.UniqueConstraint('Nombre'),
    sa.UniqueConstraint('Slug')
    )
    op.create_table('RelMenuRoles',
    sa.Column('MenuRolId', sa.Integer(), nullable=False),
    sa.Column('MenuId', sa.Integer(), nullable=False),
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['MenuId'], ['Menus.MenuId'], ),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.RolId'], ),
    sa.PrimaryKeyConstraint('MenuRolId')
    )
    op.create_table('RelRolPermisos',
    sa.Column('RolPermisoId', sa.Integer(), nullable=False),
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('PermisoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermisoId'], ['Permisos.PermisoId'], ),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.RolId'], ),
    sa.PrimaryKeyConstraint('RolPermisoId')
    )
    op.create_table('RelUsuarioRoles',
    sa.Column('UsuarioRolId', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.RolId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('UsuarioRolId')
    )
    op.add_column('Roles', sa.Column('Descripcion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Roles', 'Descripcion')
    op.drop_table('RelUsuarioRoles')
    op.drop_table('RelRolPermisos')
    op.drop_table('RelMenuRoles')
    op.drop_table('Permisos')
    op.drop_table('Menus')
    # ### end Alembic commands ###
