"""catalogo estatus de pago

Revision ID: 5aa49f685659
Revises: 866fd2c5c891
Create Date: 2026-03-12 12:13:46.819594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa49f685659'
down_revision: Union[str, Sequence[str], None] = '866fd2c5c891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoEstatusPago',
    sa.Column('EstatusPagoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EstatusPagoId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoEstatusPago')
    # ### end Alembic commands ###
