"""fix campo SolicitudId en EquipoTemporal

Revision ID: 5ca4987a6207
Revises: 92033348ca71
Create Date: 2026-03-24 13:14:53.767519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca4987a6207'
down_revision: Union[str, Sequence[str], None] = '92033348ca71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EquipoTemporal', sa.Column('SolicitudId', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('FK__EquipoTem__Solit__2BFE89A6'), 'EquipoTemporal', type_='foreignkey')
    op.create_foreign_key(None, 'EquipoTemporal', 'Solicitudes', ['SolicitudId'], ['SolicitudId'])
    op.drop_column('EquipoTemporal', 'SolititudId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EquipoTemporal', sa.Column('SolititudId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'EquipoTemporal', type_='foreignkey')
    op.create_foreign_key(op.f('FK__EquipoTem__Solit__2BFE89A6'), 'EquipoTemporal', 'Solicitudes', ['SolititudId'], ['SolicitudId'])
    op.drop_column('EquipoTemporal', 'SolicitudId')
    # ### end Alembic commands ###
