"""seed_estados_validacion

Revision ID: 61de96ad8607
Revises: ee05824d04cb
Create Date: 2026-02-24 11:42:12.007085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61de96ad8607'
down_revision: Union[str, Sequence[str], None] = 'ee05824d04cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET IDENTITY_INSERT "CatalogoEstadosValidacion" ON')
    
    op.bulk_insert(
        sa.table('CatalogoEstadosValidacion',
            sa.column('EstadoValidacionId', sa.Integer),
            sa.column('Nombre', sa.String)
        ),
        [
            {'EstadoValidacionId': 1, 'Nombre': 'APROBADO'},
            {'EstadoValidacionId': 2, 'Nombre': 'PENDIENTE'},
            {'EstadoValidacionId': 3, 'Nombre': 'RECHAZADO'},
        ]
    )
    
    op.execute('SET IDENTITY_INSERT "CatalogoEstadosValidacion" OFF')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "CatalogoEstadosValidacion" WHERE "EstadoValidacionId" IN (1, 2, 3)')
    # ### end Alembic commands ###
