"""seed catalogo documentos

Revision ID: 71115304ef00
Revises: 3275cdb793b5
Create Date: 2026-03-03 13:43:05.446634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71115304ef00'
down_revision: Union[str, Sequence[str], None] = '3275cdb793b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET IDENTITY_INSERT "CatalogoDocumentos" ON')
    
    op.bulk_insert(
        sa.table('CatalogoDocumentos',
            sa.column('DocumentoId', sa.Integer),
            sa.column('NombreDocumento', sa.String(100)),
            sa.column('Descripcion', sa.String(200)),
            sa.column('TipoArchivoId', sa.Integer)
        ),
        [
            {"DocumentoId": 1, "NombreDocumento": "Comprobante de pago", "Descripcion": "Comprobante de pago de afiliación", "TipoArchivoId": 1},
            {"DocumentoId": 2, "NombreDocumento": "INE", "Descripcion": "INE vigente", "TipoArchivoId": 1},
            {"DocumentoId": 3, "NombreDocumento": "CURP", "Descripcion": "CURP vigente", "TipoArchivoId": 1},
            {"DocumentoId": 4, "NombreDocumento": "Acta de nacimiento", "Descripcion": "Acta de nacimiento vigente", "TipoArchivoId": 1},
            {"DocumentoId": 5, "NombreDocumento": "Licencia de conducir", "Descripcion": "Licencia de conducir vigente", "TipoArchivoId": 1},
            {"DocumentoId": 6, "NombreDocumento": "Pasaporte", "Descripcion": "Pasaporte vigente", "TipoArchivoId": 1},
            {"DocumentoId": 7, "NombreDocumento": "Constancia de estudios", "Descripcion": "Constancia de estudios vigente", "TipoArchivoId": 1},
            {"DocumentoId": 8, "NombreDocumento": "Fotografía", "Descripcion": "Fotografía del afiliado", "TipoArchivoId": 1}

        ]
    )

    op.execute('SET IDENTITY_INSERT "CatalogoDocumentos" OFF')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "CatalogoDocumentos" WHERE "DocumentoId" IN (1, 2, 3, 4, 5, 6, 7, 8)')
    # ### end Alembic commands ###
