"""solicitud nula

Revision ID: 71fbcc1617bb
Revises: 421ce919ee77
Create Date: 2026-03-23 15:47:26.844449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fbcc1617bb'
down_revision: Union[str, Sequence[str], None] = '421ce919ee77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EquipoTemporal', 'SolititudId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EquipoTemporal', 'SolititudId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
