"""add_whatsapp_fields_to_invitacion

Revision ID: 757a9c1ad7c5
Revises: a45ea0f27b5f
Create Date: 2026-06-16 12:06:34.659016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '757a9c1ad7c5'
down_revision: Union[str, Sequence[str], None] = 'a45ea0f27b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.create_index(op.f('ix_AntecedentesInternacionales_AntecedentesId'), 'AntecedentesInternacionales', ['AntecedentesId'], unique=False)
    op.alter_column('Auditoria', 'FechaAccion',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(sysdatetime())'))
    op.drop_index(op.f('IX_Auditoria_Entidad_Registro'), table_name='Auditoria')
    op.drop_index(op.f('IX_Auditoria_Fecha'), table_name='Auditoria')
    op.drop_index(op.f('IX_Auditoria_Usuario'), table_name='Auditoria')
    op.alter_column('CatalogoCategorias', 'NombreCategoria',
               existing_type=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_CatalogoCategorias_CategoriaId'), 'CatalogoCategorias', ['CategoriaId'], unique=False)
    op.alter_column('CatalogoModalidad', 'NombreModalidad',
               existing_type=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_CatalogoModalidad_ModalidadId'), 'CatalogoModalidad', ['ModalidadId'], unique=False)
    op.alter_column('CatalogoRamas', 'Nombre',
               existing_type=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_CatalogoRamas_RamaId'), 'CatalogoRamas', ['RamaId'], unique=False)
    op.alter_column('CatalogoTiposSolicitud', 'Nombre',
               existing_type=sa.NVARCHAR(length=255, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('DocumentoAfiliacion', 'DocumentoPersonaId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'DocumentoAfiliacion', 'CatalogoDocumentosPersonas', ['DocumentoPersonaId'], ['DocumentosPersonasId'])
    op.alter_column('EquipoTemporal', 'FechaExpiracion',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_Equipos_EquipoId'), 'Equipos', ['EquipoId'], unique=False)
    op.create_index(op.f('ix_EquiposJugando_EquiposJugandoId'), 'EquiposJugando', ['EquiposJugandoId'], unique=False)
    op.alter_column('Ligas', 'Nombreliga',
               existing_type=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Ligas', 'Descripcionliga',
               existing_type=sa.NVARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('Ligas', 'ModalidadId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Ligas', 'CategoriaId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Ligas', 'RamaId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_Ligas_LigaId'), 'Ligas', ['LigaId'], unique=False)
    op.create_index(op.f('ix_MiembrosEquipo_MiembroEquipoId'), 'MiembrosEquipo', ['MiembroEquipoId'], unique=False)
    op.alter_column('OrdenDePago', 'SolicitudId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('PresidenteInvitacion', sa.Column('WhatsAppMessageId', sa.String(length=255), nullable=True))
    op.add_column('PresidenteInvitacion', sa.Column('WhatsAppStatus', sa.String(length=50), nullable=True))
    op.alter_column('PresidenteInvitacion', 'FechaCreacion',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('PresidenteInvitacion', 'FechaExpiracion',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('PresidenteInvitacion', 'FechaUltimoAcceso',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('IX_PresidenteInvitacion_UsuarioId'), table_name='PresidenteInvitacion')
    op.create_index(op.f('ix_RolesDeEquipo_RolId'), 'RolesDeEquipo', ['RolId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RolesDeEquipo_RolId'), table_name='RolesDeEquipo')
    op.create_index(op.f('IX_PresidenteInvitacion_UsuarioId'), 'PresidenteInvitacion', ['UsuarioId'], unique=False)
    op.alter_column('PresidenteInvitacion', 'FechaUltimoAcceso',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('PresidenteInvitacion', 'FechaExpiracion',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('PresidenteInvitacion', 'FechaCreacion',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.drop_column('PresidenteInvitacion', 'WhatsAppStatus')
    op.drop_column('PresidenteInvitacion', 'WhatsAppMessageId')
    op.alter_column('OrdenDePago', 'SolicitudId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_MiembrosEquipo_MiembroEquipoId'), table_name='MiembrosEquipo')
    op.drop_index(op.f('ix_Ligas_LigaId'), table_name='Ligas')
    op.alter_column('Ligas', 'RamaId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Ligas', 'CategoriaId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Ligas', 'ModalidadId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Ligas', 'Descripcionliga',
               existing_type=sa.String(length=200),
               type_=sa.NVARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.alter_column('Ligas', 'Nombreliga',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_EquiposJugando_EquiposJugandoId'), table_name='EquiposJugando')
    op.drop_index(op.f('ix_Equipos_EquipoId'), table_name='Equipos')
    op.alter_column('EquipoTemporal', 'FechaExpiracion',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.drop_constraint(None, 'DocumentoAfiliacion', type_='foreignkey')
    op.alter_column('DocumentoAfiliacion', 'DocumentoPersonaId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('CatalogoTiposSolicitud', 'Nombre',
               existing_type=sa.String(length=256),
               type_=sa.NVARCHAR(length=255, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_CatalogoRamas_RamaId'), table_name='CatalogoRamas')
    op.alter_column('CatalogoRamas', 'Nombre',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_CatalogoModalidad_ModalidadId'), table_name='CatalogoModalidad')
    op.alter_column('CatalogoModalidad', 'NombreModalidad',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_CatalogoCategorias_CategoriaId'), table_name='CatalogoCategorias')
    op.alter_column('CatalogoCategorias', 'NombreCategoria',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=20, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)
    op.create_index(op.f('IX_Auditoria_Usuario'), 'Auditoria', ['UsuarioId'], unique=False)
    op.create_index(op.f('IX_Auditoria_Fecha'), 'Auditoria', ['FechaAccion'], unique=False)
    op.create_index(op.f('IX_Auditoria_Entidad_Registro'), 'Auditoria', ['EntidadAfectada', 'RegistroId'], unique=False)
    op.alter_column('Auditoria', 'FechaAccion',
               existing_type=sa.DateTime(timezone=True),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysdatetime())'))
    op.drop_index(op.f('ix_AntecedentesInternacionales_AntecedentesId'), table_name='AntecedentesInternacionales')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B617ED7BE26'))
    )
    # ### end Alembic commands ###
