"""catalogo tipos archivos2

Revision ID: 7acce014970e
Revises: ca912e950757
Create Date: 2026-03-03 13:24:24.420500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acce014970e'
down_revision: Union[str, Sequence[str], None] = 'ca912e950757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoTiposArchivo',
    sa.Column('TipoArchivoId', sa.Integer(), nullable=False),
    sa.Column('NombreTipoArchivo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('TipoArchivoId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoTiposArchivo')
    # ### end Alembic commands ###
