"""fk tipo afiliacion en solicitud

Revision ID: 7cbda649293e
Revises: a7ae6468f7b1
Create Date: 2026-03-03 12:22:11.311572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbda649293e'
down_revision: Union[str, Sequence[str], None] = 'a7ae6468f7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Solicitudes', sa.Column('TipoAfiliacionId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Solicitudes', 'CatalogoTiposAfiliacion', ['TipoAfiliacionId'], ['TipoAfiliacionId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Solicitudes', type_='foreignkey')
    op.drop_column('Solicitudes', 'TipoAfiliacionId')
    # ### end Alembic commands ###
