"""seed para tipo de documentos

Revision ID: 82778414099b
Revises: b9648637638f
Create Date: 2026-03-06 10:50:13.623680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82778414099b'
down_revision: Union[str, Sequence[str], None] = 'b9648637638f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    catalogo_tipos_documento = sa.table('CatalogoTiposDocumento',
        sa.column('TipoDocumentoId', sa.Integer),
        sa.column('Nombre', sa.String)
    )

    op.execute('SET IDENTITY_INSERT CatalogoTiposDocumento ON')

    op.bulk_insert(catalogo_tipos_documento,
        [
            {"TipoDocumentoId": 1, "Nombre": "Fotografia"},
            {"TipoDocumentoId": 2, "Nombre": "Identificacion"},
            {"TipoDocumentoId": 3, "Nombre": "Personal"}
        ]
    )
    
    op.execute('SET IDENTITY_INSERT CatalogoTiposDocumento OFF')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "CatalogoTiposDocumento" WHERE "TipoDocumentoId" IN (1, 2, 3)')
    # ### end Alembic commands ###
