"""catalogo estatus presidente equipo

Revision ID: 85e5ff03e6e4
Revises: 1eaf217238bb
Create Date: 2026-03-18 12:55:48.104576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e5ff03e6e4'
down_revision: Union[str, Sequence[str], None] = '1eaf217238bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoEstatusPresidenteEquipo',
    sa.Column('EstatusPresidenteId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EstatusPresidenteId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoEstatusPresidenteEquipo')
    # ### end Alembic commands ###
