"""catalogo conceptos

Revision ID: 866fd2c5c891
Revises: cf46fa6b57c1
Create Date: 2026-03-12 12:10:51.167908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866fd2c5c891'
down_revision: Union[str, Sequence[str], None] = 'cf46fa6b57c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoConceptos',
    sa.Column('ConceptoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ConceptoId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoConceptos')
    # ### end Alembic commands ###
