"""orden de pago

Revision ID: 8d89794a41f0
Revises: 5aa49f685659
Create Date: 2026-03-12 12:29:55.212759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d89794a41f0'
down_revision: Union[str, Sequence[str], None] = '5aa49f685659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrdenDePago',
    sa.Column('OrdenPagoId', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('FechaDePago', sa.DateTime(), nullable=True),
    sa.Column('FechaEnvio', sa.DateTime(), nullable=True),
    sa.Column('RutaVoucher', sa.String(), nullable=True),
    sa.Column('EstatusPagoId', sa.Integer(), nullable=False),
    sa.Column('TotalPagar', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['EstatusPagoId'], ['CatalogoEstatusPago.EstatusPagoId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('OrdenPagoId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrdenDePago')
    # ### end Alembic commands ###
