"""catalogo tipos documentos

Revision ID: 914b9cbccdd4
Revises: c62bae392214
Create Date: 2026-03-04 15:36:42.161435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914b9cbccdd4'
down_revision: Union[str, Sequence[str], None] = 'c62bae392214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoTiposDocumento',
    sa.Column('TipoDocumentoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('TipoDocumentoId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoTiposDocumento')
    # ### end Alembic commands ###
