"""fecha de solicitud nula

Revision ID: 92033348ca71
Revises: f29bb17d6900
Create Date: 2026-03-24 11:34:10.111688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92033348ca71'
down_revision: Union[str, Sequence[str], None] = 'f29bb17d6900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Solicitudes', 'FechaSolicitud',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Solicitudes', 'FechaSolicitud',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
