"""persona nula en equipo temporal

Revision ID: 9430dc58adbb
Revises: 71fbcc1617bb
Create Date: 2026-03-23 15:54:53.139416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9430dc58adbb'
down_revision: Union[str, Sequence[str], None] = '71fbcc1617bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EquipoTemporalJugador', 'PersonaId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EquipoTemporalJugador', 'PersonaId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
