"""add personaid to documentos entregados

Revision ID: 9d426bbe45ab
Revises: 4b63f11e0289
Create Date: 2026-03-04 16:12:01.466370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d426bbe45ab'
down_revision: Union[str, Sequence[str], None] = '4b63f11e0289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DocumentosEntregadosSolicitud', sa.Column('PersonaId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'DocumentosEntregadosSolicitud', 'Personas', ['PersonaId'], ['PersonaId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DocumentosEntregadosSolicitud', type_='foreignkey')
    op.drop_column('DocumentosEntregadosSolicitud', 'PersonaId')
    # ### end Alembic commands ###
