"""bdd limpia

Revision ID: a45ea0f27b5f
Revises: 
Create Date: 2026-03-27 10:09:38.269399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45ea0f27b5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoConceptos',
    sa.Column('ConceptoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ConceptoId')
    )
    op.create_table('CatalogoEstadosValidacion',
    sa.Column('EstadoValidacionId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('EstadoValidacionId'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('CatalogoEstatusPago',
    sa.Column('EstatusPagoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EstatusPagoId')
    )
    op.create_table('CatalogoEstatusPresidenteEquipo',
    sa.Column('EstatusPresidenteId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EstatusPresidenteId')
    )
    op.create_table('CatalogoRolesPersonas',
    sa.Column('RolPersonaId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('RolPersonaId')
    )
    op.create_table('CatalogoSeguros',
    sa.Column('SeguroId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=True),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('Precio', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('SeguroId')
    )
    op.create_table('CatalogoSexo',
    sa.Column('SexoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('SexoId'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('CatalogoTipoProceso',
    sa.Column('TipoProcesoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('TipoProcesoId')
    )
    op.create_table('CatalogoTiposAfiliacion',
    sa.Column('TipoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('NombreAfiliacion', sa.String(length=100), nullable=False),
    sa.Column('CostoActual', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('TipoAfiliacionId')
    )
    op.create_table('CatalogoTiposArchivo',
    sa.Column('TipoArchivoId', sa.Integer(), nullable=False),
    sa.Column('NombreTipoArchivo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('TipoArchivoId')
    )
    op.create_table('CatalogoTiposDocumento',
    sa.Column('TipoDocumentoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('TipoDocumentoId')
    )
    op.create_table('Menus',
    sa.Column('MenuId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Ruta', sa.String(length=255), nullable=True),
    sa.Column('Icono', sa.String(length=100), nullable=True),
    sa.Column('Orden', sa.Integer(), nullable=True),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.Column('MenuPadreId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MenuPadreId'], ['Menus.MenuId'], ),
    sa.PrimaryKeyConstraint('MenuId')
    )
    op.create_table('Permisos',
    sa.Column('PermisoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Slug', sa.String(length=100), nullable=False),
    sa.Column('Descripcion', sa.String(length=255), nullable=True),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('PermisoId'),
    sa.UniqueConstraint('Nombre'),
    sa.UniqueConstraint('Slug')
    )
    op.create_table('Roles',
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=40), nullable=False),
    sa.Column('Descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('RolId'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('CatalogoDocumentos',
    sa.Column('DocumentoId', sa.Integer(), nullable=False),
    sa.Column('NombreDocumento', sa.String(length=100), nullable=False),
    sa.Column('Descripcion', sa.String(length=200), nullable=True),
    sa.Column('TipoArchivoId', sa.Integer(), nullable=True),
    sa.Column('TipoDocumentoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TipoArchivoId'], ['CatalogoTiposArchivo.TipoArchivoId'], ),
    sa.ForeignKeyConstraint(['TipoDocumentoId'], ['CatalogoTiposDocumento.TipoDocumentoId'], ),
    sa.PrimaryKeyConstraint('DocumentoId'),
    sa.UniqueConstraint('NombreDocumento')
    )
    op.create_table('Personas',
    sa.Column('PersonaId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('PrimerApellido', sa.String(length=50), nullable=False),
    sa.Column('SegundoApellido', sa.String(length=50), nullable=True),
    sa.Column('CURP', sa.CHAR(length=18), nullable=True),
    sa.Column('RFC', sa.CHAR(length=13), nullable=True),
    sa.Column('NUI', sa.String(length=60), nullable=True),
    sa.Column('SexoId', sa.Integer(), nullable=True),
    sa.Column('FechaNacimiento', sa.Date(), nullable=True),
    sa.CheckConstraint('LEN(CURP) = 18', name='check_curp_persona_longitud'),
    sa.CheckConstraint('LEN(RFC) = 13', name='check_rfc_persona_longitud'),
    sa.ForeignKeyConstraint(['SexoId'], ['CatalogoSexo.SexoId'], ),
    sa.PrimaryKeyConstraint('PersonaId')
    )
    op.create_index(op.f('ix_Personas_CURP'), 'Personas', ['CURP'], unique=False)
    op.create_index(op.f('ix_Personas_NUI'), 'Personas', ['NUI'], unique=False)
    op.create_table('RelMenuRoles',
    sa.Column('MenuRolId', sa.Integer(), nullable=False),
    sa.Column('MenuId', sa.Integer(), nullable=False),
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['MenuId'], ['Menus.MenuId'], ),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.RolId'], ),
    sa.PrimaryKeyConstraint('MenuRolId')
    )
    op.create_table('RelRolPermisos',
    sa.Column('RolPermisoId', sa.Integer(), nullable=False),
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('PermisoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PermisoId'], ['Permisos.PermisoId'], ),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.RolId'], ),
    sa.PrimaryKeyConstraint('RolPermisoId')
    )
    op.create_table('CatalogoDocumentosPersonas',
    sa.Column('DocumentosPersonasId', sa.Integer(), nullable=False),
    sa.Column('DocumentoId', sa.Integer(), nullable=False),
    sa.Column('RolPersonaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DocumentoId'], ['CatalogoDocumentos.DocumentoId'], ),
    sa.ForeignKeyConstraint(['RolPersonaId'], ['CatalogoRolesPersonas.RolPersonaId'], ),
    sa.PrimaryKeyConstraint('DocumentosPersonasId')
    )
    op.create_table('PresidentesDeEquipo',
    sa.Column('PresidenteEquipoId', sa.Integer(), nullable=False),
    sa.Column('PersonaId', sa.Integer(), nullable=False),
    sa.Column('EstatusId', sa.Integer(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['EstatusId'], ['CatalogoEstatusPresidenteEquipo.EstatusPresidenteId'], ),
    sa.ForeignKeyConstraint(['PersonaId'], ['Personas.PersonaId'], ),
    sa.PrimaryKeyConstraint('PresidenteEquipoId')
    )
    op.create_table('Usuarios',
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('PersonaId', sa.Integer(), nullable=False),
    sa.Column('Correo', sa.String(length=100), nullable=False),
    sa.Column('Contrasena', sa.String(length=256), nullable=False),
    sa.Column('Salt', sa.String(length=32), nullable=False),
    sa.Column('Estatus', sa.Boolean(), nullable=False),
    sa.Column('Eliminado', sa.Boolean(), nullable=False),
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PersonaId'], ['Personas.PersonaId'], ),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.RolId'], ),
    sa.PrimaryKeyConstraint('UsuarioId')
    )
    op.create_index(op.f('ix_Usuarios_Correo'), 'Usuarios', ['Correo'], unique=True)
    op.create_table('DocumentoAfiliacion',
    sa.Column('DocumentoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('TipoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('DocumentoPersonaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DocumentoPersonaId'], ['CatalogoDocumentosPersonas.DocumentosPersonasId'], ),
    sa.ForeignKeyConstraint(['TipoAfiliacionId'], ['CatalogoTiposAfiliacion.TipoAfiliacionId'], ),
    sa.PrimaryKeyConstraint('DocumentoAfiliacionId')
    )
    op.create_table('OrdenDePago',
    sa.Column('OrdenPagoId', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('FechaDePago', sa.DateTime(), nullable=True),
    sa.Column('FechaEnvio', sa.DateTime(), nullable=True),
    sa.Column('RutaVoucher', sa.String(), nullable=True),
    sa.Column('EstatusPagoId', sa.Integer(), nullable=False),
    sa.Column('TotalPagar', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['EstatusPagoId'], ['CatalogoEstatusPago.EstatusPagoId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('OrdenPagoId')
    )
    op.create_table('RelUsuarioRoles',
    sa.Column('UsuarioRolId', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('RolId', sa.Integer(), nullable=False),
    sa.Column('Estatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.RolId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('UsuarioRolId')
    )
    op.create_table('Solicitudes',
    sa.Column('SolicitudId', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('FechaSolicitud', sa.DateTime(), nullable=True),
    sa.Column('ObservacionesSolicitud', sa.String(length=500), nullable=True),
    sa.Column('EstatusValidacion', sa.Integer(), nullable=False),
    sa.Column('TipoAfiliacionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EstatusValidacion'], ['CatalogoEstadosValidacion.EstadoValidacionId'], ),
    sa.ForeignKeyConstraint(['TipoAfiliacionId'], ['CatalogoTiposAfiliacion.TipoAfiliacionId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('SolicitudId')
    )
    op.create_table('DocumentosEntregadosSolicitud',
    sa.Column('DocumentosSolicitudId', sa.Integer(), nullable=False),
    sa.Column('PersonaId', sa.Integer(), nullable=True),
    sa.Column('SolicitudId', sa.Integer(), nullable=True),
    sa.Column('DocumentoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('RutaArchivo', sa.String(length=512), nullable=False),
    sa.Column('FechaEntrega', sa.DateTime(), nullable=False),
    sa.Column('FechaValidacion', sa.DateTime(), nullable=True),
    sa.Column('ObservacionesDocumento', sa.String(length=500), nullable=True),
    sa.Column('EstadoValidacionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DocumentoAfiliacionId'], ['DocumentoAfiliacion.DocumentoAfiliacionId'], ),
    sa.ForeignKeyConstraint(['EstadoValidacionId'], ['CatalogoEstadosValidacion.EstadoValidacionId'], ),
    sa.ForeignKeyConstraint(['PersonaId'], ['Personas.PersonaId'], ),
    sa.ForeignKeyConstraint(['SolicitudId'], ['Solicitudes.SolicitudId'], ),
    sa.PrimaryKeyConstraint('DocumentosSolicitudId')
    )
    op.create_table('EquipoTemporal',
    sa.Column('EquipoTemporalId', sa.Integer(), nullable=False),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('CantidadJugadoresPagados', sa.Integer(), nullable=True),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('SolicitudId', sa.Integer(), nullable=True),
    sa.Column('OrdenPagoId', sa.Integer(), nullable=False),
    sa.Column('TipoProcesoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['OrdenPagoId'], ['OrdenDePago.OrdenPagoId'], ),
    sa.ForeignKeyConstraint(['SolicitudId'], ['Solicitudes.SolicitudId'], ),
    sa.ForeignKeyConstraint(['TipoProcesoId'], ['CatalogoTipoProceso.TipoProcesoId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('EquipoTemporalId')
    )
    op.create_table('OrdenPagoDetalle',
    sa.Column('OrdenPagoDetalleId', sa.Integer(), nullable=False),
    sa.Column('OrdenPagoId', sa.Integer(), nullable=False),
    sa.Column('TipoAfiliacionId', sa.Integer(), nullable=True),
    sa.Column('TipoConceptoId', sa.Integer(), nullable=True),
    sa.Column('SeguroId', sa.Integer(), nullable=True),
    sa.Column('Cantidad', sa.Integer(), nullable=True),
    sa.Column('PrecioUnitarioCobrado', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('Subtotal', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['OrdenPagoId'], ['OrdenDePago.OrdenPagoId'], ),
    sa.ForeignKeyConstraint(['SeguroId'], ['CatalogoSeguros.SeguroId'], ),
    sa.ForeignKeyConstraint(['TipoAfiliacionId'], ['CatalogoTiposAfiliacion.TipoAfiliacionId'], ),
    sa.ForeignKeyConstraint(['TipoConceptoId'], ['CatalogoConceptos.ConceptoId'], ),
    sa.PrimaryKeyConstraint('OrdenPagoDetalleId')
    )
    op.create_table('EquipoTemporalJugador',
    sa.Column('EquipoTemporalJugadorId', sa.Integer(), nullable=False),
    sa.Column('Completo', sa.Boolean(), nullable=False),
    sa.Column('EquipoTemporalId', sa.Integer(), nullable=False),
    sa.Column('PersonaId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EquipoTemporalId'], ['EquipoTemporal.EquipoTemporalId'], ),
    sa.ForeignKeyConstraint(['PersonaId'], ['Personas.PersonaId'], ),
    sa.PrimaryKeyConstraint('EquipoTemporalJugadorId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EquipoTemporalJugador')
    op.drop_table('OrdenPagoDetalle')
    op.drop_table('EquipoTemporal')
    op.drop_table('DocumentosEntregadosSolicitud')
    op.drop_table('Solicitudes')
    op.drop_table('RelUsuarioRoles')
    op.drop_table('OrdenDePago')
    op.drop_table('DocumentoAfiliacion')
    op.drop_index(op.f('ix_Usuarios_Correo'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_table('PresidentesDeEquipo')
    op.drop_table('CatalogoDocumentosPersonas')
    op.drop_table('RelRolPermisos')
    op.drop_table('RelMenuRoles')
    op.drop_index(op.f('ix_Personas_NUI'), table_name='Personas')
    op.drop_index(op.f('ix_Personas_CURP'), table_name='Personas')
    op.drop_table('Personas')
    op.drop_table('CatalogoDocumentos')
    op.drop_table('Roles')
    op.drop_table('Permisos')
    op.drop_table('Menus')
    op.drop_table('CatalogoTiposDocumento')
    op.drop_table('CatalogoTiposArchivo')
    op.drop_table('CatalogoTiposAfiliacion')
    op.drop_table('CatalogoTipoProceso')
    op.drop_table('CatalogoSexo')
    op.drop_table('CatalogoSeguros')
    op.drop_table('CatalogoRolesPersonas')
    op.drop_table('CatalogoEstatusPresidenteEquipo')
    op.drop_table('CatalogoEstatusPago')
    op.drop_table('CatalogoEstadosValidacion')
    op.drop_table('CatalogoConceptos')
    # ### end Alembic commands ###
