"""Seed tipos afiliacion

Revision ID: a7ae6468f7b1
Revises: ed28f1d63751
Create Date: 2026-03-03 12:10:09.391258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ae6468f7b1'
down_revision: Union[str, Sequence[str], None] = 'ed28f1d63751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    catalogo_afiliacion = sa.table('CatalogoTiposAfiliacion',
        sa.column('TipoAfiliacionId', sa.Integer),
        sa.column('NombreAfiliacion', sa.String(100))
    )
    
    op.execute("SET IDENTITY_INSERT CatalogoTiposAfiliacion ON")
    
    op.bulk_insert(catalogo_afiliacion,
        [
            {"TipoAfiliacionId": 1, "NombreAfiliacion": "PresidenteLiga"},
            {"TipoAfiliacionId": 2, "NombreAfiliacion": "PresidenteEquipo"},
            {"TipoAfiliacionId": 3, "NombreAfiliacion": "Entrenador"},
            {"TipoAfiliacionId": 4, "NombreAfiliacion": "JugadorMayor"},
            {"TipoAfiliacionId": 5, "NombreAfiliacion": "JugadorMenor"},
        ]
    )
    
    op.execute("SET IDENTITY_INSERT CatalogoTiposAfiliacion OFF")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM CatalogoTiposAfiliacion WHERE TipoAfiliacionId IN (1, 2, 3, 4, 5)")
