"""equipo temporal tabla 2

Revision ID: ad5929969e3a
Revises: 232f149298de
Create Date: 2026-03-20 15:38:04.810875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5929969e3a'
down_revision: Union[str, Sequence[str], None] = '232f149298de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EquipoTemporal',
    sa.Column('EquipoTemporalId', sa.Integer(), nullable=False),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('CantidadJugadoresPagados', sa.Integer(), nullable=True),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('SolititudId', sa.Integer(), nullable=False),
    sa.Column('OrdenPagoId', sa.Integer(), nullable=False),
    sa.Column('TipoProcesoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['OrdenPagoId'], ['OrdenDePago.OrdenPagoId'], ),
    sa.ForeignKeyConstraint(['SolititudId'], ['Solicitudes.SolicitudId'], ),
    sa.ForeignKeyConstraint(['TipoProcesoId'], ['CatalogoTipoProceso.TipoProcesoId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('EquipoTemporalId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EquipoTemporal')
    # ### end Alembic commands ###
