"""campo fk tipo documento

Revision ID: add2602fe93a
Revises: 914b9cbccdd4
Create Date: 2026-03-04 15:41:06.705189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add2602fe93a'
down_revision: Union[str, Sequence[str], None] = '914b9cbccdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CatalogoDocumentos', sa.Column('TipoDocumentoId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'CatalogoDocumentos', 'CatalogoTiposDocumento', ['TipoDocumentoId'], ['TipoDocumentoId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CatalogoDocumentos', type_='foreignkey')
    op.drop_column('CatalogoDocumentos', 'TipoDocumentoId')
    # ### end Alembic commands ###
