"""solicitud id nulo para documentos

Revision ID: b154cc696184
Revises: c7470e52d166
Create Date: 2026-03-19 15:31:04.257900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b154cc696184'
down_revision: Union[str, Sequence[str], None] = 'c7470e52d166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DocumentosEntregadosSolicitud', 'SolicitudId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DocumentosEntregadosSolicitud', 'SolicitudId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
