"""catalogo de proceso de equipo temporal2

Revision ID: b299d7898b32
Revises: 4c878bfe0af9
Create Date: 2026-03-20 14:08:18.897979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b299d7898b32'
down_revision: Union[str, Sequence[str], None] = '4c878bfe0af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoTipoProceso',
    sa.Column('TipoProceso', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('TipoProceso')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoTipoProceso')
    # ### end Alembic commands ###
