"""actualizacion usuarios

Revision ID: b9648637638f
Revises: 9d426bbe45ab
Create Date: 2026-03-04 16:19:39.130116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9648637638f'
down_revision: Union[str, Sequence[str], None] = '9d426bbe45ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column('Usuarios', sa.Column('PersonaId', sa.Integer(), nullable=False))

    op.drop_index(op.f('ix_Usuarios_CURP'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_NUI'), table_name='Usuarios')

    op.drop_constraint(op.f('FK__Usuarios__SexoId__4CA06362'), 'Usuarios', type_='foreignkey')

    op.create_foreign_key(None, 'Usuarios', 'Personas', ['PersonaId'], ['PersonaId'])

    # eliminar default constraints antes de borrar columnas
    op.execute("""
    DECLARE @sql NVARCHAR(MAX) = '';
    SELECT @sql += 'ALTER TABLE Usuarios DROP CONSTRAINT ' + dc.name + ';'
    FROM sys.default_constraints dc
    JOIN sys.columns c 
        ON dc.parent_object_id = c.object_id 
        AND dc.parent_column_id = c.column_id
    WHERE OBJECT_NAME(dc.parent_object_id) = 'Usuarios'
    AND c.name IN ('PrimerApellido','FechaNacimiento','SexoId','RFC','Nombre','SegundoApellido','NUI','CURP');

    EXEC sp_executesql @sql;
    """)

    op.drop_column('Usuarios', 'PrimerApellido')
    op.drop_column('Usuarios', 'FechaNacimiento')
    op.drop_column('Usuarios', 'SexoId')
    op.drop_constraint('check_rfc_longitud', 'Usuarios', type_='check')
    op.drop_column('Usuarios', 'RFC')
    op.drop_column('Usuarios', 'Nombre')
    op.drop_column('Usuarios', 'SegundoApellido')
    op.drop_column('Usuarios', 'NUI')
    op.drop_constraint('check_curp_longitud', 'Usuarios', type_='check')
    op.drop_column('Usuarios', 'CURP')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('CURP', sa.CHAR(length=18, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Usuarios', sa.Column('NUI', sa.VARCHAR(length=60, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Usuarios', sa.Column('SegundoApellido', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Usuarios', sa.Column('Nombre', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Usuarios', sa.Column('RFC', sa.CHAR(length=13, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('Usuarios', sa.Column('SexoId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Usuarios', sa.Column('FechaNacimiento', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('Usuarios', sa.Column('PrimerApellido', sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Usuarios__SexoId__4CA06362'), 'Usuarios', 'CatalogoSexo', ['SexoId'], ['SexoId'])
    op.create_index(op.f('ix_Usuarios_NUI'), 'Usuarios', ['NUI'], unique=False)
    op.create_index(op.f('ix_Usuarios_CURP'), 'Usuarios', ['CURP'], unique=False)
    op.drop_column('Usuarios', 'PersonaId')
    # ### end Alembic commands ###
