"""crear entidad persona2

Revision ID: c62bae392214
Revises: 2c8748fc7092
Create Date: 2026-03-04 15:22:43.409585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62bae392214'
down_revision: Union[str, Sequence[str], None] = '2c8748fc7092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personas',
    sa.Column('PersonaId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('PrimerApellido', sa.String(length=50), nullable=False),
    sa.Column('SegundoApellido', sa.String(length=50), nullable=True),
    sa.Column('CURP', sa.CHAR(length=18), nullable=True),
    sa.Column('RFC', sa.CHAR(length=13), nullable=True),
    sa.Column('NUI', sa.String(length=60), nullable=True),
    sa.Column('SexoId', sa.Integer(), nullable=True),
    sa.Column('FechaNacimiento', sa.Date(), nullable=True),
    sa.CheckConstraint('LEN(CURP) = 18', name='check_curp_persona_longitud'),
    sa.CheckConstraint('LEN(RFC) = 13', name='check_rfc_persona_longitud'),
    sa.ForeignKeyConstraint(['SexoId'], ['CatalogoSexo.SexoId'], ),
    sa.PrimaryKeyConstraint('PersonaId')
    )
    op.create_index(op.f('ix_Personas_CURP'), 'Personas', ['CURP'], unique=False)
    op.create_index(op.f('ix_Personas_NUI'), 'Personas', ['NUI'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Personas_NUI'), table_name='Personas')
    op.drop_index(op.f('ix_Personas_CURP'), table_name='Personas')
    op.drop_table('Personas')
    # ### end Alembic commands ###
