"""tabla presidentes de equipo2

Revision ID: c7470e52d166
Revises: db693ff801f9
Create Date: 2026-03-18 14:26:09.024339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7470e52d166'
down_revision: Union[str, Sequence[str], None] = 'db693ff801f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PresidentesDeEquipo',
    sa.Column('PresidenteEquipoId', sa.Integer(), nullable=False),
    sa.Column('PersonaId', sa.Integer(), nullable=False),
    sa.Column('EstatusId', sa.Integer(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['EstatusId'], ['CatalogoEstatusPresidenteEquipo.EstatusPresidenteId'], ),
    sa.ForeignKeyConstraint(['PersonaId'], ['Personas.PersonaId'], ),
    sa.PrimaryKeyConstraint('PresidenteEquipoId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PresidentesDeEquipo')
    # ### end Alembic commands ###
