"""campo costo de afiliacion

Revision ID: c993b271323d
Revises: 816e3bbc473b
Create Date: 2026-03-13 12:27:09.947481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c993b271323d'
down_revision: Union[str, Sequence[str], None] = '816e3bbc473b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CatalogoTiposAfiliacion', sa.Column('CostoActual', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CatalogoTiposAfiliacion', 'CostoActual')
    # ### end Alembic commands ###
