"""catalogo seguros

Revision ID: cf46fa6b57c1
Revises: 70c03263d8f2
Create Date: 2026-03-12 12:05:30.492166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf46fa6b57c1'
down_revision: Union[str, Sequence[str], None] = '70c03263d8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoSeguros',
    sa.Column('SeguroId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=True),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('Precio', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('SeguroId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoSeguros')
    # ### end Alembic commands ###
