"""initial migration

Revision ID: d1a2c0022ed8
Revises: 
Create Date: 2026-02-17 12:13:34.709366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a2c0022ed8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoSexo',
    sa.Column('SexoId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('SexoId'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('Roles',
    sa.Column('IdRol', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('IdRol'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('Usuarios',
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('PrimerApellido', sa.String(length=50), nullable=False),
    sa.Column('SegundoApellido', sa.String(length=50), nullable=True),
    sa.Column('CURP', sa.CHAR(length=18), nullable=True),
    sa.Column('RFC', sa.CHAR(length=13), nullable=True),
    sa.Column('NUI', sa.String(length=60), nullable=True),
    sa.Column('SexoId', sa.Integer(), nullable=True),
    sa.Column('FechaNacimiento', sa.Date(), nullable=True),
    sa.Column('Correo', sa.String(length=100), nullable=False),
    sa.Column('Contrasena', sa.String(length=256), nullable=False),
    sa.Column('Estatus', sa.Boolean(), nullable=False),
    sa.Column('Eliminado', sa.Boolean(), nullable=False),
    sa.Column('Salt', sa.String(length=32), nullable=False),
    sa.CheckConstraint('LEN(CURP) = 18', name='check_curp_longitud'),
    sa.CheckConstraint('LEN(RFC) = 13', name='check_rfc_longitud'),
    sa.ForeignKeyConstraint(['SexoId'], ['CatalogoSexo.SexoId'], ),
    sa.PrimaryKeyConstraint('UsuarioId')
    )
    op.create_index(op.f('ix_Usuarios_CURP'), 'Usuarios', ['CURP'], unique=False)
    op.create_index(op.f('ix_Usuarios_Correo'), 'Usuarios', ['Correo'], unique=True)
    op.create_index(op.f('ix_Usuarios_NUI'), 'Usuarios', ['NUI'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuarios_NUI'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_Correo'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_CURP'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_table('Roles')
    op.drop_table('CatalogoSexo')
    # ### end Alembic commands ###
