"""seed tipos archivo

Revision ID: d993b2cf9507
Revises: 7acce014970e
Create Date: 2026-03-03 13:28:01.754711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd993b2cf9507'
down_revision: Union[str, Sequence[str], None] = '7acce014970e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET IDENTITY_INSERT "CatalogoTiposArchivo" ON')

    op.bulk_insert(
        sa.table('CatalogoTiposArchivo',
            sa.column('TipoArchivoId', sa.Integer),
            sa.column('NombreTipoArchivo', sa.String(100))
        ),
        [
            {"TipoArchivoId": 1, "NombreTipoArchivo": "pdf"},
            {"TipoArchivoId": 2, "NombreTipoArchivo": "png"},
            {"TipoArchivoId": 3, "NombreTipoArchivo": "jpg"},
            {"TipoArchivoId": 4, "NombreTipoArchivo": "jpeg"},
            {"TipoArchivoId": 5, "NombreTipoArchivo": "xlsx"}
        ]
    )

    op.execute('SET IDENTITY_INSERT "CatalogoTiposArchivo" OFF')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "CatalogoTiposArchivo" WHERE "TipoArchivoId" IN (1, 2, 3, 4, 5)')
    # ### end Alembic commands ###
