"""Detalles de orden de pago2

Revision ID: e44f04fde9b3
Revises: faa40b14935c
Create Date: 2026-03-12 12:46:36.489855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44f04fde9b3'
down_revision: Union[str, Sequence[str], None] = 'faa40b14935c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrdenPagoDetalle',
    sa.Column('OrdenPagoDetalleId', sa.Integer(), nullable=False),
    sa.Column('TipoAfiliacionId', sa.Integer(), nullable=True),
    sa.Column('TipoConceptoId', sa.Integer(), nullable=True),
    sa.Column('SeguroId', sa.Integer(), nullable=True),
    sa.Column('Cantidad', sa.Integer(), nullable=True),
    sa.Column('PrecioUnitarioCobrado', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('Subtotal', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['SeguroId'], ['CatalogoSeguros.SeguroId'], ),
    sa.ForeignKeyConstraint(['TipoAfiliacionId'], ['CatalogoTiposAfiliacion.TipoAfiliacionId'], ),
    sa.ForeignKeyConstraint(['TipoConceptoId'], ['CatalogoConceptos.ConceptoId'], ),
    sa.PrimaryKeyConstraint('OrdenPagoDetalleId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrdenPagoDetalle')
    # ### end Alembic commands ###
