"""documentos de personas2

Revision ID: e534cd6aeba6
Revises: b06f9acbff6e
Create Date: 2026-03-06 13:26:15.475836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e534cd6aeba6'
down_revision: Union[str, Sequence[str], None] = 'b06f9acbff6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoDocumentosPersonas',
    sa.Column('DocumentosPersonasId', sa.Integer(), nullable=False),
    sa.Column('DocumentoId', sa.Integer(), nullable=False),
    sa.Column('RolPersonaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DocumentoId'], ['CatalogoDocumentos.DocumentoId'], ),
    sa.ForeignKeyConstraint(['RolPersonaId'], ['CatalogoRolesPersonas.RolPersonaId'], ),
    sa.PrimaryKeyConstraint('DocumentosPersonasId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoDocumentosPersonas')
    # ### end Alembic commands ###
