"""Crear catalogo tipos afiliacion2

Revision ID: ed28f1d63751
Revises: 125fec629970
Create Date: 2026-03-03 12:07:11.468711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed28f1d63751'
down_revision: Union[str, Sequence[str], None] = '125fec629970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoTiposAfiliacion',
    sa.Column('TipoAfiliacionId', sa.Integer(), nullable=False),
    sa.Column('NombreAfiliacion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('TipoAfiliacionId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CatalogoTiposAfiliacion')
    # ### end Alembic commands ###
