"""crearsolicitudes

Revision ID: ee05824d04cb
Revises: ceef1ee79e95
Create Date: 2026-02-24 11:39:06.505231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee05824d04cb'
down_revision: Union[str, Sequence[str], None] = 'ceef1ee79e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CatalogoEstadosValidacion',
    sa.Column('EstadoValidacionId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('EstadoValidacionId'),
    sa.UniqueConstraint('Nombre')
    )
    op.create_table('Solicitudes',
    sa.Column('SolicitudId', sa.Integer(), nullable=False),
    sa.Column('UsuarioId', sa.Integer(), nullable=False),
    sa.Column('FechaSolicitud', sa.DateTime(), nullable=False),
    sa.Column('ObservacionesSolicitud', sa.String(length=500), nullable=True),
    sa.Column('EstatusValidacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EstatusValidacion'], ['CatalogoEstadosValidacion.EstadoValidacionId'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.UsuarioId'], ),
    sa.PrimaryKeyConstraint('SolicitudId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Solicitudes')
    op.drop_table('CatalogoEstadosValidacion')
    # ### end Alembic commands ###
