from enum import Enum

class Rol(str, Enum):
    ADMINISTRADOR = "ADMINISTRADOR"
    PRESIDENTE_LIGA = "PRESIDENTE_LIGA"
    PRESIDENTE_EQUIPO = "PRESIDENTE_EQUIPO"
    ENTRENADOR = "ENTRENADOR"
    JUGADOR = "JUGADOR"
    TUTOR = "TUTOR"
    MASTER = "MASTER"